//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Objects;
    using System.Data.Objects.DataClasses;
    using System.Linq;
    
    public partial class HR_DBEntities : DbContext
    {
        public HR_DBEntities()
            : base("name=HR_DBEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<bonus> bonus { get; set; }
        public DbSet<config_file_first_kind> config_file_first_kind { get; set; }
        public DbSet<config_file_second_kind> config_file_second_kind { get; set; }
        public DbSet<config_file_third_kind> config_file_third_kind { get; set; }
        public DbSet<config_major> config_major { get; set; }
        public DbSet<config_major_kind> config_major_kind { get; set; }
        public DbSet<config_major_professional> config_major_professional { get; set; }
        public DbSet<config_primary_key> config_primary_key { get; set; }
        public DbSet<config_public_char> config_public_char { get; set; }
        public DbSet<config_question_first_kind> config_question_first_kind { get; set; }
        public DbSet<config_question_second_kind> config_question_second_kind { get; set; }
        public DbSet<engage_answer> engage_answer { get; set; }
        public DbSet<engage_answer_details> engage_answer_details { get; set; }
        public DbSet<engage_exam> engage_exam { get; set; }
        public DbSet<engage_exam_details> engage_exam_details { get; set; }
        public DbSet<engage_interview> engage_interview { get; set; }
        public DbSet<engage_major_release> engage_major_release { get; set; }
        public DbSet<engage_resume> engage_resume { get; set; }
        public DbSet<engage_subjects> engage_subjects { get; set; }
        public DbSet<human_file> human_file { get; set; }
        public DbSet<human_file_dig> human_file_dig { get; set; }
        public DbSet<major_change> major_change { get; set; }
        public DbSet<Permission> Permission { get; set; }
        public DbSet<RightsObject> RightsObject { get; set; }
        public DbSet<Role> Role { get; set; }
        public DbSet<salary_grant> salary_grant { get; set; }
        public DbSet<salary_grant_details> salary_grant_details { get; set; }
        public DbSet<salary_project> salary_project { get; set; }
        public DbSet<salary_standard> salary_standard { get; set; }
        public DbSet<salary_standard_details> salary_standard_details { get; set; }
        public DbSet<training> training { get; set; }
        public DbSet<users> users { get; set; }
        public DbSet<vw_usersAndRole> vw_usersAndRole { get; set; }
    
        public virtual int procDanHao(ObjectParameter danhao)
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("procDanHao", danhao);
        }
    
        public virtual int procSalaryGrant(ObjectParameter danhao)
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("procSalaryGrant", danhao);
        }
    }
}
