//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class HR_DBEntities : DbContext
    {
        public HR_DBEntities()
            : base("name=HR_DBEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
        /// <summary>
        /// 激励登记表
        /// </summary>
        public virtual DbSet<bonus> bonus { get; set; }
        /// <summary>
        /// 一级机构设置
        /// </summary>
        public virtual DbSet<config_file_first_kind> config_file_first_kind { get; set; }
        /// <summary>
        /// 二级机构设置
        /// </summary>
        public virtual DbSet<config_file_second_kind> config_file_second_kind { get; set; }
        /// <summary>
        /// 三级机构设置
        /// </summary>
        public virtual DbSet<config_file_third_kind> config_file_third_kind { get; set; }
        /// <summary>
        /// 职位分类设置
        /// </summary>
        public virtual DbSet<config_major> config_major { get; set; }
        /// <summary>
        /// 职位部门表
        /// </summary>
        public virtual DbSet<config_major_kind> config_major_kind { get; set; }
        /// <summary>
        /// 职位表
        /// </summary>
        public virtual DbSet<config_major_professional> config_major_professional { get; set; }
        /// <summary>
        /// 关键字设置表
        /// </summary>
        public virtual DbSet<config_primary_key> config_primary_key { get; set; }
        /// <summary>
        /// 公共字段设置，包括薪酬设置，职称设置，国籍，民族，宗教信仰，政治面貌，教育年限，学历,专业，特长，爱好，培训项目，培训成绩，奖励项目，奖励等级
        /// </summary>
        public virtual DbSet<config_public_char> config_public_char { get; set; }
        /// <summary>
        /// 试题一级分类设置
        /// </summary>
        public virtual DbSet<config_question_first_kind> config_question_first_kind { get; set; }
        /// <summary>
        /// 试题二级分类设置
        /// </summary>
        public virtual DbSet<config_question_second_kind> config_question_second_kind { get; set; }
        /// <summary>
        /// 考试答题登记表 
        /// </summary>
        public virtual DbSet<engage_answer> engage_answer { get; set; }
        /// <summary>
        /// 考试答题详细信息
        /// </summary>
        public virtual DbSet<engage_answer_details> engage_answer_details { get; set; }
        /// <summary>
        /// 试卷登记表
        /// </summary>
        public virtual DbSet<engage_exam> engage_exam { get; set; }
        /// <summary>
        /// 试卷详细信息
        /// </summary>
        public virtual DbSet<engage_exam_details> engage_exam_details { get; set; }
        /// <summary>
        /// 面试表
        /// </summary>
        public virtual DbSet<engage_interview> engage_interview { get; set; }
        /// <summary>
        /// 职位发表登记表
        /// </summary>
        public virtual DbSet<engage_major_release> engage_major_release { get; set; }
        /// <summary>
        /// 简历管理
        /// </summary>
        public virtual DbSet<engage_resume> engage_resume { get; set; }
        /// <summary>
        /// 试题题库登记表
        /// </summary>
        public virtual DbSet<engage_subjects> engage_subjects { get; set; }
        /// <summary>
        /// 人力资源档案
        /// </summary>
        public virtual DbSet<human_file> human_file { get; set; }
        /// <summary>
        /// 记录人力资源档案所做的任何更改
        /// </summary>
        public virtual DbSet<human_file_dig> human_file_dig { get; set; }
        /// <summary>
        /// 职位调动表
        /// </summary>
        public virtual DbSet<major_change> major_change { get; set; }
        /// <summary>
        /// 薪酬发放登记表
        /// </summary>
        public virtual DbSet<salary_grant> salary_grant { get; set; }
        /// <summary>
        /// 薪酬发放详细信息
        /// </summary>
        public virtual DbSet<salary_grant_details> salary_grant_details { get; set; }
        /// <summary>
        /// 薪酬报销分类
        /// </summary>
        public virtual DbSet<salary_project> salary_project { get; set; }
        /// <summary>
        /// 薪酬标准基本信息表
        /// </summary>
        public virtual DbSet<salary_standard> salary_standard { get; set; }
        /// <summary>
        /// 薪酬标准单详细信息表
        /// </summary>
        public virtual DbSet<salary_standard_details> salary_standard_details { get; set; }
        /// <summary>
        /// 培训登记表
        /// </summary>
        public virtual DbSet<training> training { get; set; }
        /// <summary>
        /// 用户表
        /// </summary>
        public virtual DbSet<users> users { get; set; }
        /// <summary>
        /// 生成单号
        /// </summary>
        /// <param name="danhao"></param>
        /// <returns></returns>
        public virtual int procDanHao(ObjectParameter danhao)
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("procDanHao", danhao);
        }
    
        public virtual int procSalaryGrant(ObjectParameter danhao)
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("procSalaryGrant", danhao);
        }
    }
}
